#!/usr/bin/env python3
"""Render docs/latest.md + recent trade_log entries → docs/index.html.

Produces a single self-contained HTML file for GitHub Pages.
"""

import os
import re
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MEMORY = ROOT / "memory"

MAX_LOG_SECTIONS = 6


# ---------------------------------------------------------------------------
# Extract recent trade-log sections
# ---------------------------------------------------------------------------

def extract_recent_sections(text: str, n: int) -> str:
    """Return the most recent `n` '## YYYY-MM-DD' sections from trade_log.md."""
    # Strip HTML comments (the format example block in trade_log.md)
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    # Split on ## headings that look like dates
    parts = re.split(r"(?=^## \d{4}-\d{2}-\d{2})", text, flags=re.MULTILINE)
    # Filter to only actual date sections
    sections = [p for p in parts if re.match(r"^## \d{4}-\d{2}-\d{2}", p)]
    # Most recent first (they're appended chronologically, so last = newest)
    recent = sections[-n:] if len(sections) > n else sections
    recent.reverse()
    return "\n".join(recent).strip()


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Weekly Trading Research</title>
<style>
:root {{
  --bg: #fafafa;
  --card: #ffffff;
  --fg: #1a1a1a;
  --muted: #666;
  --border: #e2e2e2;
  --accent: #0055aa;
  --green: #1a7a2e;
  --red: #b91c1c;
  --code-bg: #f3f3f3;
  --shadow: 0 1px 3px rgba(0,0,0,0.08);
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --bg: #161616;
    --card: #1e1e1e;
    --fg: #e0e0e0;
    --muted: #999;
    --border: #333;
    --accent: #5b9fd6;
    --green: #4aba5c;
    --red: #e5534b;
    --code-bg: #252525;
    --shadow: 0 1px 3px rgba(0,0,0,0.3);
  }}
}}
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.6;
  padding: 1.5rem;
}}
.container {{ max-width: 820px; margin: 0 auto; }}
.card {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.5rem 2rem;
  margin-bottom: 1.5rem;
  box-shadow: var(--shadow);
}}
h1 {{
  font-size: 1.5rem;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 2px solid var(--border);
}}
h2 {{
  font-size: 1.2rem;
  color: var(--accent);
  margin-top: 1.6rem;
  margin-bottom: 0.5rem;
}}
h3 {{
  font-size: 1.05rem;
  margin-top: 1.2rem;
  margin-bottom: 0.3rem;
}}
p {{ margin-bottom: 0.7rem; }}
ul, ol {{ margin: 0.3rem 0 0.7rem 1.4rem; }}
li {{ margin-bottom: 0.2rem; }}
strong {{ font-weight: 600; }}
table {{
  width: 100%;
  border-collapse: collapse;
  margin: 0.7rem 0;
  font-size: 0.85rem;
  overflow-x: auto;
  display: block;
}}
th, td {{
  text-align: left;
  padding: 0.35rem 0.5rem;
  border: 1px solid var(--border);
  white-space: nowrap;
}}
th {{ background: var(--code-bg); font-weight: 600; }}
code {{
  background: var(--code-bg);
  padding: 0.1rem 0.25rem;
  border-radius: 3px;
  font-size: 0.88em;
}}
pre {{
  background: var(--code-bg);
  padding: 0.8rem 1rem;
  border-radius: 4px;
  overflow-x: auto;
  margin: 0.5rem 0;
}}
pre code {{ background: none; padding: 0; }}
blockquote {{
  border-left: 3px solid var(--accent);
  padding-left: 1rem;
  color: var(--muted);
  margin: 0.5rem 0;
}}
.section-label {{
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--muted);
  margin-bottom: 0.3rem;
}}
footer {{
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.82rem;
  text-align: center;
}}
footer a {{ color: var(--accent); }}
</style>
</head>
<body>
<div class="container">

  <div class="card">
    <div class="section-label">This week</div>
    {latest_html}
  </div>

  {log_card}

  <footer>
    Generated by <a href="https://github.com/{repo}">trading-agent</a>
  </footer>

</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def render_md(text: str) -> str:
    """Convert markdown to HTML with table and fenced-code support."""
    return markdown.markdown(text, extensions=["tables", "fenced_code"])


def main() -> None:
    # Latest report
    latest_path = DOCS / "latest.md"
    if not latest_path.exists():
        print("docs/latest.md not found — skipping render")
        return
    latest_html = render_md(latest_path.read_text(encoding="utf-8"))

    # Trade log (recent entries)
    log_path = MEMORY / "trade_log.md"
    log_card = ""
    if log_path.exists():
        log_text = log_path.read_text(encoding="utf-8")
        recent = extract_recent_sections(log_text, MAX_LOG_SECTIONS)
        if recent:
            log_html = render_md(recent)
            log_card = (
                '<div class="card">\n'
                '    <div class="section-label">Recent picks</div>\n'
                f"    {log_html}\n"
                "  </div>"
            )

    # Repo link from GitHub Actions env, fallback for local runs
    repo = os.environ.get("GITHUB_REPOSITORY", "trading-agent")

    html = TEMPLATE.format(
        latest_html=latest_html,
        log_card=log_card,
        repo=repo,
    )

    out = DOCS / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"Rendered {out}")


if __name__ == "__main__":
    main()
